version: 0.2

run-as: root

env:
  parameter-store:
    MongoDb_url: "/ayush/mongodburl"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing...
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo "MONGODB_URI=$mongo_url" > .env
      - cat .env
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - '**/*'
    - echo Uploaded Artifacts
